build::
	GOOS=linux GOARCH=amd64 go build -o ./functions/onConnect/handler ./functions/onConnect/handler.go

	GOOS=linux GOARCH=amd64 go build -o ./functions/onDisconnect/handler ./functions/onDisconnect/handler.go

	GOOS=linux GOARCH=amd64 go build -o ./functions/onMessage/handler ./functions/onMessage/handler.go
